

Data: https://trynkalab.sanger.ac.uk/

Publication: https://www.nature.com/articles/s41588-022-01066-3#data-availability

taking the lowly active cells as a small example

```
wget -c https://trynka.cog.sanger.ac.uk/stimulatedCells_lowlyActiveCD4_HVGs_processed.h5ad
```



```{r}
library(iSEE)
library(iSEEu)
library(zellkonverter)


sce_gosia <- readH5AD("~/Downloads/stimulatedCells_lowlyActiveCD4_HVGs_processed.h5ad")

modeEmpty(sce_gosia)

iSEE(sce_gosia)
```


After navigating around, we have a "good" initial configuration



```{r}
initial <- list()

################################################################################
# Settings for Reduced dimension plot 1
################################################################################

initial[["ReducedDimensionPlot1"]] <- new("ReducedDimensionPlot", Type = "X_umap", XAxis = 1L, YAxis = 2L, 
    FacetRowByColData = "X10X_operator", FacetColumnByColData = "X10X_operator", 
    ColorByColumnData = "Cluster_id", ColorByFeatureNameAssay = "X", 
    ColorBySampleNameColor = "#FF0000", ShapeByColumnData = "X10X_operator", 
    SizeByColumnData = "Age", TooltipColumnData = character(0), 
    FacetRowBy = "None", FacetColumnBy = "None", ColorBy = "Column data", 
    ColorByDefaultColor = "#000000", ColorByFeatureName = "ISG15", 
    ColorByFeatureSource = "---", ColorByFeatureDynamicSource = FALSE, 
    ColorBySampleName = "AAACCTGGTCTAACGT-1-2", ColorBySampleSource = "---", 
    ColorBySampleDynamicSource = FALSE, ShapeBy = "None", SizeBy = "None", 
    SelectionAlpha = 0.1, ZoomData = numeric(0), BrushData = list(), 
    VisualBoxOpen = FALSE, VisualChoices = "Color", ContourAdd = FALSE, 
    ContourColor = "#0000FF", PointSize = 1, PointAlpha = 1, 
    Downsample = FALSE, DownsampleResolution = 200, CustomLabels = FALSE, 
    CustomLabelsText = "AAACCTGGTCTAACGT-1-2", FontSize = 1, 
    LegendPointSize = 1, LegendPosition = "Bottom", HoverInfo = TRUE, 
    LabelCenters = FALSE, LabelCentersBy = "X10X_operator", LabelCentersColor = "#000000", 
    VersionInfo = list(iSEE = structure(list(c(2L, 10L, 0L)), class = c("package_version", 
    "numeric_version"))), PanelId = 1L, PanelHeight = 500L, PanelWidth = 4L, 
    SelectionBoxOpen = FALSE, RowSelectionSource = "---", ColumnSelectionSource = "---", 
    DataBoxOpen = FALSE, RowSelectionDynamicSource = FALSE, ColumnSelectionDynamicSource = FALSE, 
    RowSelectionRestrict = FALSE, ColumnSelectionRestrict = FALSE, 
    SelectionHistory = list())

################################################################################
# Settings for Row data table 1
################################################################################

initial[["RowDataTable1"]] <- new("RowDataTable", Selected = "ISG15", Search = "", SearchColumns = c("", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
""), HiddenColumns = character(0), VersionInfo = list(iSEE = structure(list(
    c(2L, 10L, 0L)), class = c("package_version", "numeric_version"
))), PanelId = 1L, PanelHeight = 500L, PanelWidth = 4L, SelectionBoxOpen = FALSE, 
    RowSelectionSource = "---", ColumnSelectionSource = "---", 
    DataBoxOpen = FALSE, RowSelectionDynamicSource = FALSE, ColumnSelectionDynamicSource = FALSE, 
    RowSelectionRestrict = FALSE, ColumnSelectionRestrict = FALSE, 
    SelectionHistory = list())

################################################################################
# Settings for Feature assay plot 1
################################################################################

initial[["FeatureAssayPlot1"]] <- new("FeatureAssayPlot", Assay = "X", XAxis = "Column data", XAxisColumnData = "Cluster_id", 
    XAxisFeatureName = "ISG15", XAxisFeatureSource = "---", XAxisFeatureDynamicSource = FALSE, 
    YAxisFeatureName = "ISG15", YAxisFeatureSource = "RowDataTable1", 
    YAxisFeatureDynamicSource = FALSE, FacetRowByColData = "X10X_operator", 
    FacetColumnByColData = "X10X_operator", ColorByColumnData = "X10X_operator", 
    ColorByFeatureNameAssay = "X", ColorBySampleNameColor = "#FF0000", 
    ShapeByColumnData = "X10X_operator", SizeByColumnData = "Age", 
    TooltipColumnData = character(0), FacetRowBy = "None", FacetColumnBy = "None", 
    ColorBy = "None", ColorByDefaultColor = "#000000", ColorByFeatureName = "ISG15", 
    ColorByFeatureSource = "---", ColorByFeatureDynamicSource = FALSE, 
    ColorBySampleName = "AAACCTGGTCTAACGT-1-2", ColorBySampleSource = "---", 
    ColorBySampleDynamicSource = FALSE, ShapeBy = "None", SizeBy = "None", 
    SelectionAlpha = 0.1, ZoomData = numeric(0), BrushData = list(), 
    VisualBoxOpen = FALSE, VisualChoices = "Color", ContourAdd = FALSE, 
    ContourColor = "#0000FF", PointSize = 1, PointAlpha = 1, 
    Downsample = FALSE, DownsampleResolution = 200, CustomLabels = FALSE, 
    CustomLabelsText = "AAACCTGGTCTAACGT-1-2", FontSize = 1, 
    LegendPointSize = 1, LegendPosition = "Bottom", HoverInfo = TRUE, 
    LabelCenters = FALSE, LabelCentersBy = "X10X_operator", LabelCentersColor = "#000000", 
    VersionInfo = list(iSEE = structure(list(c(2L, 10L, 0L)), class = c("package_version", 
    "numeric_version"))), PanelId = 1L, PanelHeight = 500L, PanelWidth = 4L, 
    SelectionBoxOpen = FALSE, RowSelectionSource = "---", ColumnSelectionSource = "---", 
    DataBoxOpen = FALSE, RowSelectionDynamicSource = FALSE, ColumnSelectionDynamicSource = FALSE, 
    RowSelectionRestrict = FALSE, ColumnSelectionRestrict = FALSE, 
    SelectionHistory = list())

################################################################################
# Settings for Reduced dimension plot 2
################################################################################

initial[["ReducedDimensionPlot2"]] <- new("ReducedDimensionPlot", Type = "X_umap", XAxis = 1L, YAxis = 2L, 
    FacetRowByColData = "X10X_operator", FacetColumnByColData = "X10X_operator", 
    ColorByColumnData = "X10X_operator", ColorByFeatureNameAssay = "X", 
    ColorBySampleNameColor = "#FF0000", ShapeByColumnData = "X10X_operator", 
    SizeByColumnData = "Age", TooltipColumnData = character(0), 
    FacetRowBy = "None", FacetColumnBy = "None", ColorBy = "Feature name", 
    ColorByDefaultColor = "#000000", ColorByFeatureName = "ISG15", 
    ColorByFeatureSource = "RowDataTable1", ColorByFeatureDynamicSource = FALSE, 
    ColorBySampleName = "AAACCTGGTCTAACGT-1-2", ColorBySampleSource = "---", 
    ColorBySampleDynamicSource = FALSE, ShapeBy = "None", SizeBy = "None", 
    SelectionAlpha = 0.1, ZoomData = numeric(0), BrushData = list(), 
    VisualBoxOpen = TRUE, VisualChoices = "Color", ContourAdd = FALSE, 
    ContourColor = "#0000FF", PointSize = 1, PointAlpha = 1, 
    Downsample = FALSE, DownsampleResolution = 200, CustomLabels = FALSE, 
    CustomLabelsText = "AAACCTGGTCTAACGT-1-2", FontSize = 1, 
    LegendPointSize = 1, LegendPosition = "Bottom", HoverInfo = TRUE, 
    LabelCenters = FALSE, LabelCentersBy = "X10X_operator", LabelCentersColor = "#000000", 
    VersionInfo = list(iSEE = structure(list(c(2L, 10L, 0L)), class = c("package_version", 
    "numeric_version"))), PanelId = 2L, PanelHeight = 500L, PanelWidth = 4L, 
    SelectionBoxOpen = FALSE, RowSelectionSource = "---", ColumnSelectionSource = "---", 
    DataBoxOpen = FALSE, RowSelectionDynamicSource = FALSE, ColumnSelectionDynamicSource = FALSE, 
    RowSelectionRestrict = FALSE, ColumnSelectionRestrict = FALSE, 
    SelectionHistory = list())

################################################################################
# Settings for Reduced dimension plot 3
################################################################################

initial[["ReducedDimensionPlot3"]] <- new("ReducedDimensionPlot", Type = "X_umap", XAxis = 1L, YAxis = 2L, 
    FacetRowByColData = "X10X_operator", FacetColumnByColData = "X10X_operator", 
    ColorByColumnData = "Activation_pseudotime", ColorByFeatureNameAssay = "X", 
    ColorBySampleNameColor = "#FF0000", ShapeByColumnData = "X10X_operator", 
    SizeByColumnData = "Age", TooltipColumnData = character(0), 
    FacetRowBy = "None", FacetColumnBy = "None", ColorBy = "Column data", 
    ColorByDefaultColor = "#000000", ColorByFeatureName = "ISG15", 
    ColorByFeatureSource = "---", ColorByFeatureDynamicSource = FALSE, 
    ColorBySampleName = "AAACCTGGTCTAACGT-1-2", ColorBySampleSource = "---", 
    ColorBySampleDynamicSource = FALSE, ShapeBy = "None", SizeBy = "None", 
    SelectionAlpha = 0.1, ZoomData = numeric(0), BrushData = list(), 
    VisualBoxOpen = TRUE, VisualChoices = "Color", ContourAdd = FALSE, 
    ContourColor = "#0000FF", PointSize = 1, PointAlpha = 1, 
    Downsample = FALSE, DownsampleResolution = 200, CustomLabels = FALSE, 
    CustomLabelsText = "AAACCTGGTCTAACGT-1-2", FontSize = 1, 
    LegendPointSize = 1, LegendPosition = "Bottom", HoverInfo = TRUE, 
    LabelCenters = FALSE, LabelCentersBy = "X10X_operator", LabelCentersColor = "#000000", 
    VersionInfo = list(iSEE = structure(list(c(2L, 10L, 0L)), class = c("package_version", 
    "numeric_version"))), PanelId = 3L, PanelHeight = 500L, PanelWidth = 4L, 
    SelectionBoxOpen = FALSE, RowSelectionSource = "---", ColumnSelectionSource = "---", 
    DataBoxOpen = FALSE, RowSelectionDynamicSource = FALSE, ColumnSelectionDynamicSource = FALSE, 
    RowSelectionRestrict = FALSE, ColumnSelectionRestrict = FALSE, 
    SelectionHistory = list())

################################################################################
# Settings for Complex heatmap 1
################################################################################

initial[["ComplexHeatmapPlot1"]] <- new("ComplexHeatmapPlot", Assay = "X", CustomRows = TRUE, CustomRowsText = "ISG15\nIL7R\nCD52\nGIMAP7\nCXCR4\nSTAT1\nIRF1\nIFIT3\nGBP1", 
    ClusterRows = FALSE, ClusterRowsDistance = "spearman", ClusterRowsMethod = "ward.D2", 
    DataBoxOpen = FALSE, VisualChoices = "Annotations", ColumnData = "Cell_population", 
    RowData = character(0), CustomBounds = FALSE, LowerBound = NA_real_, 
    UpperBound = NA_real_, AssayCenterRows = FALSE, AssayScaleRows = FALSE, 
    DivergentColormap = "purple < black < yellow", ShowDimNames = "Rows", 
    LegendPosition = "Bottom", LegendDirection = "Horizontal", 
    VisualBoxOpen = FALSE, NamesRowFontSize = 10, NamesColumnFontSize = 10, 
    ShowColumnSelection = TRUE, OrderColumnSelection = TRUE, 
    VersionInfo = list(iSEE = structure(list(c(2L, 10L, 0L)), class = c("package_version", 
    "numeric_version"))), PanelId = 1L, PanelHeight = 500L, PanelWidth = 4L, 
    SelectionBoxOpen = FALSE, RowSelectionSource = "---", ColumnSelectionSource = "---", 
    RowSelectionDynamicSource = FALSE, ColumnSelectionDynamicSource = FALSE, 
    RowSelectionRestrict = FALSE, ColumnSelectionRestrict = FALSE, 
    SelectionHistory = list())



```


```{r}
tour_resting <- read.delim("tour_resting.txt", sep = ";", header = TRUE)
```


## Running the fully fledged instance of iSEE

This is just it ðŸ’£ ðŸ’£ ðŸ’£ ðŸ’£ ðŸ’£ 

(and this is the line that starts the app, fully configured)

```{r}
iSEE(sce_gosia, initial = initial, appTitle = "iSEE â¤ï¸ resting cells dataset")
```

To start the app with the tour running, you can just run this command:

```{r}
iSEE(sce_gosia, initial = initial, appTitle = "iSEE â¤ï¸ resting cells dataset",
     tour = tour_resting)
```

